### ISSUE TITLE
로그인 페이지 -> 메인페이지 로 이동될 때 메모리

### ISSUE THREAD

**Issue by jihoonahn** [neulsom-EZY/EZY-ios#148]
<img width="1792" alt="2021-10-09_10 15 46" src="https://user-images.githubusercontent.com/68891494/136661644-7c1f219d-18d8-47c7-acf3-3c8a71c77472.png">

로그인에서 메인페이지로 로그인 하고 이동 하는데 메모리가 한눈에 보이게 많이 듭니다.

**Comment by Y00ujin** [comment]
현재 제 맥북에서는 7mb정도가 늘어서 다른 이유를 조사해보고 코드도 한번 살펴보겠습니다 🧐
