### ISSUE TITLE
EZY.xcodeproj와 같은 IDE 에서 생성되는 file을 .gitignore 해주세요

### ISSUE THREAD

**Issue by siwony** [neulsom-EZY/EZY-ios#5]
`EZY.xcodeproj`와같이 IDE에서 생성되거나 프로젝트에서 컴파일되거나 빌드될때 생성되는 파일들이 있습니다.  
이러한 파일들이 github push되면 협업을 하는 과정에서 개발자마다 IDE등..에서 자동 생성되는 파일이 다를수도 있는데 
나중에 pull request시 위와같이 자동생성 되는 파일들에 의해서 complete가 발생할 확률이 매우 높습니다.

이뿐만이 아니라 프로젝트코드에 관여를 안하는 파일들이 github에 push되면 파일구조가 지저분해집니다.

이러한 이유로 EZY.xcodeproj와 같은 IDE 에서 생성되는 file을 .gitignore 해주세요

다음 사이트에서 자신의 프로젝트에 맞는` .gitignore`를 찾을 수 있습니다.
https://www.toptal.com/developers/gitignore

**Comment by Y00ujin** [comment]
<img width="196" alt="스크린샷 2021-05-29 14 43 13" src="https://user-images.githubusercontent.com/71479613/120059387-36aa0a80-c08c-11eb-9932-9c2c6ee2c75a.png">

성공적으로 .gitignore하였습니다.
